server:
  port: ${PORT:8081}

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 11MB

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: America/Guayaquil

app:
  mail:
    enabled: ${MAIL_ENABLED:false}
    api-key: ${BREVO_API_KEY:}
    from: ${MAIL_FROM:}
    from-name: ${MAIL_FROM_NAME:UNIB.E Reservas}

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000
