server:
  port: ${PORT:8081}

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 11MB

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: America/Guayaquil

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

app:
  mail:
    enabled: ${MAIL_ENABLED:false}
    from: ${MAIL_USERNAME:}

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000
